services:
  db:
    image: postgres:17-alpine
    container_name: llm_db_local
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: insights_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data_local:/var/lib/postgresql/data

  bot:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: insights_db
      PGUSERNAME: admin
      PGPASSWORD: password

volumes:
  pg_data_local:
