export const VENDOR_PREFIX_MAP: [string, string][] = [
    ["amazon-nova", "Amazon"],
    ["chatgpt", "OpenAI"],
    ["gpt-oss", "OpenAI"],
    ["chatglm", "Zhipu AI"],
    ["internlm", "Shanghai AI Lab"],
    ["magistral", "Mistral AI"],
    ["ministral", "Mistral AI"],
    ["mixtral", "Mistral AI"],
    ["mistral", "Mistral AI"],
    ["minimax", "MiniMax"],
    ["nvidia", "NVIDIA"],
    ["nemotron", "NVIDIA"],
    ["deepseek", "DeepSeek"],
    ["command", "Cohere"],
    ["c4ai", "Cohere"],
    ["claude", "Anthropic"],
    ["gemini", "Google"],
    ["gemma", "Google"],
    ["palm", "Google"],
    ["gpt", "OpenAI"],
    ["o1-", "OpenAI"],
    ["o3-", "OpenAI"],
    ["o4-", "OpenAI"],
    ["grok", "xAI"],
    ["llama", "Meta"],
    ["qwen", "Alibaba"],
    ["qwq", "Alibaba"],
    ["phi", "Microsoft"],
    ["mai", "Microsoft"],
    ["ernie", "Baidu"],
    ["glm", "Zhipu AI"],
    ["hunyuan", "Tencent"],
    ["kimi", "Moonshot AI"],
    ["seed", "Bytedance"],
    ["yi-", "01.AI"],
    ["nova-", "Amazon"],
    ["step", "StepFun"],
    ["reka", "Reka AI"],
    ["jamba", "AI21"],
    ["dbrx", "Databricks"],
    ["snowflake", "Snowflake"],
    ["olmo", "Allen AI"],
    ["granite", "IBM"],
    ["mercury", "Inception Labs"],
    ["intellect", "PrimeIntellect"],
    ["athene", "Nexusflow"],
];
